### ISSUE TITLE
win_firewall_rule Allow enabling built-in rules by using displaygroup

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/community.windows#13]
_From @kinwolfqc on Mar 05, 2020 19:28_

##### SUMMARY

In powershell, we can enable multiple rules that belong to the same displaygroup, and  many built-in rules use disaplygroups  
`Enable-NetFirewallRule -DisplayGroup "Windows Remote Management"`

The win_firewall_rule doesn't seems to allow that.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_firewall_rule

_Copied from original issue: ansible/ansible#68052_

**Comment by sakar97** [comment]
@jborean93  can I work on this?

**Comment by jborean93** [comment]
Sure, any PR will be appreciated.

**Comment by sakar97** [comment]
I came up with two Scenarios:
1- When a user is passing only the `group` and `enabled` parameter. Then it will enable all the rules in the provided group.
2- When a user is passing only the `group` and a new parameter which is something like `enableall`. Then it will enable all the rules in the group.
In both cases, I need to change the `name` parameter as optional, otherwise it will create, modify, or remove the named rule.
Any suggestions will be helpful and appreciated in implementing this new feature.

**Comment by jborean93** [comment]
I would probably prefer option 1, by passing a `group` and not `name` you are effectively saying this is the state for all rules in this group.
