### ISSUE TITLE
win_security_policy modifies the encoding of Registry key value

### ISSUE THREAD

**Issue by egvghost** [ansible-collections/community.windows#153]
##### SUMMARY

win_security_policy modifies the encoding of Registry key value MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\LegalNoticeText, changing special characters such as french accents into '?'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_security_policy

##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = None
  configured module search path = [u'/Users/egvidal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/egvidal/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/egvidal/Library/Python/2.7/bin/ansible
  python version = 2.7.16 (default, Jul  5 2020, 02:24:03) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.21) (-macos10.15-objc-
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

    target OS: Windows Server 2008
    host OS: MacOS Catalina v10.15.6

##### STEPS TO REPRODUCE

Having 'LegalNoticeText' set in 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' manually set (or via win_regedit module) with a text like:
```
'Vous utilisez un système informatique personnel appartenant à la Société, qui peut être utilisé uniquement aux fins autorisées. En cliquant sur « OK » vous acceptez les conditions d’utilisation.' 
```
after running win_security_policy module to change other settings (not this registry key), the text from this key value changes to:
```
'Vous utilisez un syst?me informatique personnel appartenant ? la Soci?t?, qui peut ?tre utilis? uniquement aux fins autoris?es. En cliquant sur ? OK ? vous acceptez les conditions d?utilisation.'
```

```
  - win_security_policy:
      section: "System Access"
      key: "PasswordComplexity"
      value: "1"
```

##### EXPECTED RESULTS

The expected behavior will be just modify what's expected, without messing up other settings.

##### ACTUAL RESULTS

The setting managed by win_security_policy module changed as expected, but somehow another setting encoding changed too. I assume that's because both are part of the 'security database' handled with secedit..

```paste below

```

**Comment by jborean93** [comment]
Just opened https://github.com/ansible-collections/community.windows/pull/156 which should fix this problem. The `secedit.exe /export` function has some weird logic when it comes to encoding the exported ini file. When testing the changes it seems to fix your problem but it would be great to get confirmation from another person.

**Comment by egvghost** [comment]
Hey Jordan, thanks for your time working on this.. How should I proceed to
test the modified module?

**Comment by jborean93** [comment]
You can place the .ps1 file into a folder called  `library` that is adjacent to your playbook. If you run with `-vvv` you should see the path used be that custom location.

**Comment by egvghost** [comment]
Hi @jborean93, thanks again for your support.. While running my playbook with this new module version, I've got the following error message:

"msg": "module (win_security_policy) is missing interpreter line"

**Comment by jborean93** [comment]
Just adding here for people reading the code that links back here.

The `LegalNoticeText` field is a funny one, the line in the ini exported by `secedit.exe` is

> MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System\LegalNoticeText=7,<value here>

The first part is the registry path to the value is set to, the `7` refers to the registry type which in this case is `REG_MULTI_SZ` and finally the remaining parts are the value to set. The `REG_MULTI_SZ` is a string type where it contains multiple entries split by `\x00`. Because it's UTF-16-LE encoded the with the value of `t` as 1 entry would be encoded as `74 00 00 00 00 00`. An entry is UTF-16-LE encoded with a null char (`74 00 00 00`) and finally one more null char is added to the end to denote the end of the whole entry. A standard `REG_SZ` entry also contains the null char at the end but because there's only 1 entry the raw value is just `74 00 00 00`.

What is happening is that `secedit.exe` is creating the raw byte value that would be expected for `REG_MULTI_SZ` but when it goes to set it in the registry it forces the property type to be `REG_SZ` and sets the binary value for a `REG_MULTI_SZ`. This means a setting of `LegalNoticeText=7,test` would become a `REG_SZ` with the raw value of `74 00 65 00 73 00 74 00 00 00 00 00` (extra null char). I would consider this a bug in `secedit` but there's nothing I can do to change it so we can at least handle this edge case by trimming the extra null char in order to preserve the original value.

An extra tidbit of information, why is the ini storing the value as a `REG_MULTI_SZ`. The reason is because `LegalNoticeText` can contain multiple lines of information but an ini entry cannot. So if the registry value was set to something like:

```
Danger do not misuse
Click to continue
```

The ini value would now become `LegalNoticeText=7,Danger do not misuse,Click to continue`. Each newline (`\r\n`) is interpreted by `secedit.exe` as a `REG_MULTI_SZ` entry. So while it's able to handle the raw input with newlines, it's unable to then reprocess that data correctly which now the module should help with.
