### ISSUE TITLE
Migrate Windows module development guide to this collection

### ISSUE THREAD

**Issue by samccann** [ansible-collections/community.windows#394]
##### SUMMARY

As per   https://github.com/ansible-community/community-topics/issues/91, all collection-specific development  guides must be migrated to their respective collections. This improves the ability of a user/developer to find this content on docs.ansible.com and for collection owners to keep this content accurate.

Please migrate the following:

- [ ] [Windows module development walkthrough](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_modules_general_windows.rst)

See https://hackmd.io/w6JSHW_XRzi9cBZtoN4snA for details. You can ask questions in the #docs irc/matrix channels if you need help.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by briantist** [comment]
I think this is probably better migrated to `ansible.windows` rather than `community.windows`.

That being said, I have a PR #391 ready to merge here for adding docs build to this collection. Hopefully with that running smoothly here, we'd do the same thing for `ansible.windows`. Moving the guide will be smoother with the assurance that the docs are being built properly, readable, all references working, etc.

I'm ok with taking on moving this guide, to whichever collection it's ultimately decided it should live in.

**Comment by samccann** [comment]
After some initial discussion - it seems portions of this windows dev guide should stay in core. @jborean93 - do you have thoughts on this? I don't want to push out guides that are still relevant to core development (aka people writing PRs on ansible/ansible repo).

**Comment by samccann** [comment]
The general consensus so far is to keep this guide in core. See https://github.com/ansible/community/issues/643#issuecomment-1180358267 and further comments there for details. We can leave this open for another week to see if any other thoughts surface, but otherwise, we should close this issue.

**Comment by samccann** [comment]
Closing this as the discussion resolved to keep the guide where it's at. Thanks everyone!
