### ISSUE TITLE
community.windows.win_domain_user - add expiration date option

### ISSUE THREAD

**Issue by monorailpilot** [ansible-collections/community.windows#404]
##### SUMMARY
Please add an option to set the domain user expiration date as part of the user creation process.

##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
community.windows.win_domain_user

##### ADDITIONAL INFORMATION
This would be useful as it currently does not exist, forcing reliance on powershell scripts.

**Comment by caidingyu** [comment]
Any update on this request? It will be helpful to have this feature. Thanks!

**Comment by jborean93** [comment]
The `win_domain_user` module has been deprecated by https://github.com/ansible-collections/community.windows/pull/516 in favour of [microsoft.ad.user](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/user_module.html#ansible-collections-microsoft-ad-user-module). See the [migration guide](https://docs.ansible.com/ansible/devel/collections/microsoft/ad/docsite/guide_migration.html#module-win-domain-user) for more info on how to change your code to use the newer module.

The `microsoft.ad.user` module can be used to set and LDAP attribute values that are needed rather than a hardcoded list that `win_domain_user` has. In this case the expiration date can be set with

```yaml
- microsoft.ad.user:
    name: name
    state: present
    attributes:
      set:
        accountExpires: ...
```
